### ISSUE TITLE
Value of INSTAFETCH_HOST

### ISSUE THREAD

**Issue by ferencik-f** [juicyfx/juicy#1813]
Hi, what should be the value of INSTAFETCH_HOST on services/instafetch?

I get the following error:
`{"message":"Protocol \"http:\" not supported. Expected \"https:\"","code":"ERR_INVALID_PROTOCOL"}`

**Comment by f3l1x** [comment]
Here is example of instahost backend.

https://github.com/f00b4r/instahost
