### ISSUE TITLE
oggo and chromium

### ISSUE THREAD

**Issue by frelle** [juicyfx/juicy#3888]
Hi,

After the install of oggo into a vercel app, there are an error when reaching the app : 

Failed to launch the browser process! /tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

I missed something during the install/copy ? 

Thank you for the help

**Comment by f3l1x** [comment]
Hi. Are you using same package and package-lock (https://github.com/juicyfx/juicy/blob/master/services/oggo/package-lock.json) as me? It's crucial.

I am using Node 14.x for oggo. Are you?

**Comment by f3l1x** [comment]
Solved via email. Placing screenshot for future generation.

![CleanShot 2023-03-05 at 20 53 06@2x](https://user-images.githubusercontent.com/538058/222982592-7890ba25-0217-4f8e-b571-3ea958a31cc1.png)
