### ISSUE TITLE
PDFx not working on Vercel

### ISSUE THREAD

**Issue by saschazesiger** [juicyfx/juicy#4466]
So, I've uploaded the Code from pdfx to my repository and published it on Vercel but I get following Error:
<img width="1304" alt="image" src="https://github.com/juicyfx/juicy/assets/76683226/8fa5e4a9-1d7d-4cab-92aa-2de0a9e69ee1">

Do I have to configure something in order for it to work? I've tried with Node.js version 16 and 18.

**Comment by f3l1x** [comment]
Hi, fixed. https://github.com/juicyfx/juicy/commit/0f86734627b373b247cccd8f9882cd52fe63a33a

**Comment by f3l1x** [comment]
You can use node 18 even node 20.
