### ISSUE TITLE
Loosen up urls

### ISSUE THREAD

**Issue by vody105** [juicyfx/juicy#498]
I suggest:

- allowing / at the end of the urls so that both of these works https://obr.now.sh/remixicon/logos/github-fill/  vs https://obr.now.sh/remixicon/logos/github-fill
- twitter icons does not support uppercase codes https://iconist.vercel.app/twemoji/1F004 vs https://iconist.vercel.app/twemoji/1f004

**Comment by f3l1x** [comment]
Solved https://github.com/juicyfx/juicy/commit/3930be6b15ace729e71e879d8ad6047d5575778c
